import type { Ranking } from "./types";

export const rankings: Ranking[] = [
  {
    id: "obesity",
    platform: "CrunchDAO",
    competition: "Obesity ML Challenge — Part 3",
    host: "Eric & Wendy Schmidt Center · Broad Institute",
    place: 2,
    highlight: true,
    placeLabel: { pt: "empatado · Peer Review", en: "tied · Peer Review", es: "empatado · Peer Review" },
    metric: { pt: "nota 2,67 / 3", en: "score 2.67 / 3", es: "nota 2,67 / 3" },
    summary: {
      pt: "Participação individual. 4,47 milhões de pares de genes pontuados por um prior aditivo ancorado no controle; genes essenciais removidos; interação testada por validação aninhada e descartada por não reproduzir. Os pares indicados seguem para laboratório.",
      en: "Individual entry. 4.47 million gene pairs scored with a control-anchored additive prior; core-essential genes removed; interaction terms tested under nested CV and dropped for not reproducing. Nominated pairs go on to wet-lab testing.",
      es: "Participación individual. 4,47 millones de pares de genes puntuados con un prior aditivo anclado al control; genes esenciales eliminados; interacciones probadas con validación anidada y descartadas por no reproducirse. Los pares nominados pasan a laboratorio.",
    },
    date: "2026",
    status: "final",
  },
  {
    id: "synth",
    platform: "CrunchDAO",
    competition: "Synth · Synthetic Price Data",
    host: "CrunchDAO · Bittensor",
    place: 22,
    placeLabel: { pt: "horizonte 1h · ranking ao vivo (16 set 2026)", en: "1h horizon · live ranking (Sep 16, 2026)", es: "horizonte 1h · ranking en vivo (16 sep 2026)" },
    metric: { pt: "anchor score 0,683", en: "anchor score 0.683", es: "anchor score 0,683" },
    summary: {
      pt: "Previsão da distribuição completa de retornos em tempo real. O ponto de virada foi perceber que o alvo eram incrementos por passo, não acumulados: o mesmo modelo foi de 55% pior a melhor que o benchmark em todos os 12 ativos.",
      en: "Real-time forecasting of full return distributions. The turning point was realizing the target was per-step increments, not cumulative moves: the same model went from 55% worse to beating the benchmark on all 12 assets.",
      es: "Pronóstico en tiempo real de distribuciones completas de retornos. El punto de inflexión fue ver que el objetivo eran incrementos por paso, no acumulados: el mismo modelo pasó de 55% peor a superar el benchmark en los 12 activos.",
    },
    date: "2026",
    status: "live",
  },
  {
    id: "adia",
    platform: "CrunchDAO",
    competition: "ADIA Lab Structural Break · Real-Time",
    host: "ADIA Lab",
    place: 178,
    field: 1603,
    placeLabel: { pt: "de 1.603 participantes (16 set 2026)", en: "of 1,603 participants (Sep 16, 2026)", es: "de 1.603 participantes (16 sep 2026)" },
    metric: { pt: "TS-AUC 62,08%", en: "TS-AUC 62.08%", es: "TS-AUC 62,08%" },
    summary: {
      pt: "Detecção online de quebra permanente de regime. Gradient boosting sobre ~100 features em streaming combinado com uma TCN causal em numpy puro, determinística. Cada submissão é versionada e reproduzível bit a bit.",
      en: "Online detection of permanent regime shifts. Streaming gradient boosting over ~100 features blended with a deterministic causal TCN in pure numpy. Every submission is tagged and bit-for-bit reproducible.",
      es: "Detección online de cambios permanentes de régimen. Gradient boosting en streaming sobre ~100 features combinado con una TCN causal determinista en numpy puro. Cada envío está versionado y es reproducible bit a bit.",
    },
    date: "set 2026",
    status: "live",
  },
  {
    id: "arc",
    platform: "Kaggle",
    competition: "ARC Prize 2026 · ARC-AGI-3",
    host: "ARC Prize Foundation",
    place: 981,
    placeLabel: { pt: "leaderboard público ao vivo (16 set 2026)", en: "live public leaderboard (Sep 16, 2026)", es: "leaderboard público en vivo (16 sep 2026)" },
    metric: { pt: "melhor score 1,15", en: "best score 1.15", es: "mejor score 1,15" },
    summary: {
      pt: "Agente híbrido para raciocínio abstrato e generalização com poucos exemplos: um LLM propõe hipóteses e um motor causal decide.",
      en: "Hybrid agent for abstract reasoning and few-shot generalization: an LLM proposes hypotheses and a causal engine decides.",
      es: "Agente híbrido para razonamiento abstracto y generalización con pocos ejemplos: un LLM propone hipótesis y un motor causal decide.",
    },
    date: "set 2026",
    status: "live",
  },
  {
    id: "knee",
    platform: "Kaggle",
    competition: "RSNA Knee Abnormality Detection",
    host: "Radiological Society of North America",
    place: 2563,
    placeLabel: { pt: "leaderboard público ao vivo (16 set 2026)", en: "live public leaderboard (Sep 16, 2026)", es: "leaderboard público en vivo (16 sep 2026)" },
    metric: { pt: "LB 0,500 → 0,858", en: "LB 0.500 → 0.858", es: "LB 0,500 → 0,858" },
    summary: {
      pt: "Detecção de anomalias em ressonância de joelho com pouquíssimos estudos rotulados: rótulos extraídos de laudos em vários idiomas e encoder DINOv2 2.5D.",
      en: "Anomaly detection in knee MRI with very few labeled studies: labels mined from multilingual radiology reports and a DINOv2 2.5D encoder.",
      es: "Detección de anomalías en resonancia de rodilla con muy pocos estudios etiquetados: etiquetas extraídas de informes multilingües y encoder DINOv2 2.5D.",
    },
    date: "set 2026",
    status: "live",
  },
];
