import type { T } from "./types";

export const ui = {
  nav: {
    services: { pt: "Serviços", en: "Services", es: "Servicios" },
    cases: { pt: "Casos", en: "Case studies", es: "Casos" },
    rankings: { pt: "Competições", en: "Competitions", es: "Competencias" },
    work: { pt: "Projetos", en: "Projects", es: "Proyectos" },
    index: { pt: "Índice", en: "Index", es: "Índice" },
    experience: { pt: "Trajetória", en: "Experience", es: "Trayectoria" },
    engagement: { pt: "Contratação", en: "Engagement", es: "Contratación" },
    writing: { pt: "Artigos", en: "Writing", es: "Artículos" },
    domains: { pt: "Áreas", en: "Expertise", es: "Áreas" },
    stack: { pt: "Tecnologias", en: "Technology", es: "Tecnologías" },
    contact: { pt: "Contato", en: "Contact", es: "Contacto" },
  },
  hero: {
    eyebrow: { pt: "Yuri Freitas · Engenheiro de Software Sênior", en: "Yuri Freitas · Senior Software Engineer", es: "Yuri Freitas · Ingeniero de Software Sénior" },
    titleA: { pt: "Engenharia de software e IA", en: "Software engineering and AI", es: "Ingeniería de software e IA" },
    titleB: { pt: "para sistemas críticos.", en: "for mission‑critical systems.", es: "para sistemas críticos." },
    lead: {
      pt: "Engenheiro de software sênior com mais de 8 anos projetando, entregando e sustentando sistemas em produção para bancos, seguradoras, saúde, varejo e energia. Atuo da automação bancária e aplicações financeiras a plataformas corporativas de IA, com foco em confiabilidade, evolução contínua e operação de longo prazo.",
      en: "Senior software engineer with 8+ years designing, delivering and sustaining production systems for banking, insurance, healthcare, retail and energy. My work spans banking automation and financial applications to corporate AI platforms, with a focus on reliability, continuous evolution and long-term operation.",
      es: "Ingeniero de software sénior con más de 8 años diseñando, entregando y sosteniendo sistemas en producción para banca, seguros, salud, retail y energía. Trabajo desde la automatización bancaria y aplicaciones financieras hasta plataformas corporativas de IA, con foco en confiabilidad, evolución continua y operación de largo plazo.",
    },
    ctaPrimary: { pt: "Solicitar proposta", en: "Request a proposal", es: "Solicitar propuesta" },
    ctaSecondary: { pt: "Ver casos", en: "See case studies", es: "Ver casos" },
    trusted: { pt: "Onde atuei", en: "Where I’ve worked", es: "Dónde trabajé" },
  },
  rankings: {
    kicker: { pt: "Competições", en: "Competitions", es: "Competencias" },
    title: { pt: "Método validado em competições internacionais.", en: "Method proven in international competitions.", es: "Método validado en competencias internacionales." },
    lead: {
      pt: "Resultados em desafios de ML com dados reais — genômica, séries temporais e raciocínio abstrato.",
      en: "Results in ML challenges on real data — genomics, time series and abstract reasoning.",
      es: "Resultados en desafíos de ML con datos reales — genómica, series temporales y razonamiento abstracto.",
    },
    top: { pt: "top", en: "top", es: "top" },
    live: { pt: "em andamento", en: "live", es: "en curso" },
    final: { pt: "final", en: "final", es: "final" },
    source: { pt: "Anúncio oficial", en: "Official announcement", es: "Anuncio oficial" },
  },
  work: {
    kicker: { pt: "Projetos em destaque", en: "Selected work", es: "Proyectos destacados" },
    title: { pt: "Projetos publicados.", en: "Published projects.", es: "Proyectos publicados." },
    repo: { pt: "Código", en: "Code", es: "Código" },
    live: { pt: "Abrir", en: "Open", es: "Abrir" },
  },
  index: {
    kicker: { pt: "Índice", en: "Index", es: "Índice" },
    title: { pt: "Todos os projetos.", en: "All projects.", es: "Todos los proyectos." },
    lead: {
      pt: "Públicos com link; privados, locais e de competições apenas citados.",
      en: "Public work is linked; private, local and competition work is only mentioned.",
      es: "Públicos con enlace; privados, locales y de competencias solo mencionados.",
    },
    all: { pt: "Tudo", en: "All", es: "Todo" },
    public: { pt: "público", en: "public", es: "público" },
    private: { pt: "privado", en: "private", es: "privado" },
    count: { pt: "projetos", en: "projects", es: "proyectos" },
    since: { pt: "desde 2017", en: "since 2017", es: "desde 2017" },
    empty: { pt: "Nada nesta categoria ainda.", en: "Nothing in this category yet.", es: "Nada en esta categoría aún." },
  },
  experience: {
    kicker: { pt: "Trajetória", en: "Experience", es: "Trayectoria" },
    title: { pt: "Experiência profissional.", en: "Work experience.", es: "Experiencia profesional." },
    skills: { pt: "Ferramentas", en: "Toolkit", es: "Herramientas" },
  },
  contact: {
    kicker: { pt: "Vamos conversar", en: "Let’s talk", es: "Hablemos" },
    title: { pt: "Tem um projeto ou um contrato em vista?", en: "Have a project or a contract in mind?", es: "¿Tiene un proyecto o un contrato en mente?" },
    body: {
      pt: "Me mande uma mensagem no LinkedIn com o contexto — respondo com os próximos passos e uma sugestão de formato. Atendo remoto, em português, inglês ou espanhol.",
      en: "Send me a LinkedIn message with some context — I’ll reply with next steps and a suggested engagement model. Remote, in Portuguese, English or Spanish.",
      es: "Envíeme un mensaje por LinkedIn con el contexto — respondo con los próximos pasos y una sugerencia de formato. Remoto, en portugués, inglés o español.",
    },
    cta: { pt: "Falar no LinkedIn", en: "Message on LinkedIn", es: "Escribir por LinkedIn" },
  },
  palette: {
    open: { pt: "Buscar", en: "Search", es: "Buscar" },
    placeholder: { pt: "Buscar projetos, competições, seções…", en: "Search projects, competitions, sections…", es: "Buscar proyectos, competencias, secciones…" },
    empty: { pt: "Nenhum resultado.", en: "No results.", es: "Sin resultados." },
    sections: { pt: "Seções", en: "Sections", es: "Secciones" },
    projects: { pt: "Projetos", en: "Projects", es: "Proyectos" },
    competitions: { pt: "Competições", en: "Competitions", es: "Competencias" },
    actions: { pt: "Ações", en: "Actions", es: "Acciones" },
    hint: { pt: "navegar · enter abrir · esc fechar", en: "navigate · enter open · esc close", es: "navegar · enter abrir · esc cerrar" },
  },
  services: {
    kicker: { pt: "Serviços", en: "Services", es: "Servicios" },
    title: { pt: "O que posso construir para a sua empresa.", en: "What I can build for your company.", es: "Lo que puedo construir para su empresa." },
    lead: {
      pt: "Do diagnóstico à operação em produção, com métricas combinadas desde o início.",
      en: "From assessment to production, with metrics agreed from day one.",
      es: "Del diagnóstico a la operación en producción, con métricas acordadas desde el inicio.",
    },
  },
  cases: {
    kicker: { pt: "Casos", en: "Case studies", es: "Casos" },
    title: { pt: "Resultados entregues em empresas reais.", en: "Results delivered at real companies.", es: "Resultados entregados en empresas reales." },
    via: { pt: "via", en: "via", es: "vía" },
  },
  engagement: {
    kicker: { pt: "Contratação", en: "Engagement", es: "Contratación" },
    title: { pt: "Formatos de trabalho.", en: "Ways to work together.", es: "Formatos de trabajo." },
    lead: {
      pt: "Contrato como pessoa jurídica. Escolha o formato que encaixa no momento da sua empresa.",
      en: "Contracted as a registered business. Pick the model that fits where your company is.",
      es: "Contrato como persona jurídica. Elija el formato que encaje con el momento de su empresa.",
    },
    popular: { pt: "Recomendado", en: "Recommended", es: "Recomendado" },
    process: { pt: "Como funciona", en: "How it works", es: "Cómo funciona" },
    cta: { pt: "Conversar", en: "Get in touch", es: "Conversar" },
  },
  writing: {
    kicker: { pt: "Artigos e publicações", en: "Writing", es: "Artículos y publicaciones" },
    title: { pt: "O que escrevi sobre o que construí.", en: "What I’ve written about what I build.", es: "Lo que escribí sobre lo que construyo." },
    posts: { pt: "Posts em destaque", en: "Featured posts", es: "Posts destacados" },
    all: { pt: "Todos no LinkedIn", en: "All on LinkedIn", es: "Todos en LinkedIn" },
  },
  domains: {
    kicker: { pt: "Áreas de atuação", en: "Areas of expertise", es: "Áreas de actuación" },
    title: { pt: "Onde empresa, competição e pesquisa se encontram.", en: "Where client work, competitions and research meet.", es: "Donde empresa, competencia e investigación se encuentran." },
    lead: {
      pt: "Cada área reúne o que entreguei para clientes, o que testei em competições internacionais e o que construí por conta própria.",
      en: "Each area brings together what I delivered for clients, what I tested in international competitions and what I built on my own.",
      es: "Cada área reúne lo que entregué a clientes, lo que probé en competencias internacionales y lo que construí por mi cuenta.",
    },
    documents: { pt: "Documentos processados", en: "Documents processed", es: "Documentos procesados" },
    timeline: { pt: "Antes da IA generativa", en: "Before generative AI", es: "Antes de la IA generativa" },
    evidence: { pt: "Onde apliquei", en: "Where I applied it", es: "Dónde lo apliqué" },
  },
  stack: {
    kicker: { pt: "Tecnologias", en: "Technology", es: "Tecnologías" },
    title: { pt: "Ferramentas que uso em produção e em pesquisa.", en: "Tools I use in production and research.", es: "Herramientas que uso en producción e investigación." },
    lead: {
      pt: "Da camada de modelo à infraestrutura, passando por avaliação, dados e interface.",
      en: "From the model layer to infrastructure, through evaluation, data and interface.",
      es: "De la capa de modelo a la infraestructura, pasando por evaluación, datos e interfaz.",
    },
    count: { pt: "tecnologias", en: "technologies", es: "tecnologías" },
    groups: { pt: "grupos", en: "groups", es: "grupos" },
    legend: { pt: "Usada em projeto de cliente ou competição — com o nome ao lado.", en: "Used in client work or a competition — named alongside.", es: "Usada en proyecto de cliente o competencia — con el nombre al lado." },
  },
  footer: {
    built: { pt: "Feito à mão com React e Vite.", en: "Handmade with React and Vite.", es: "Hecho a mano con React y Vite." },
  },
  a11y: {
    theme: { pt: "Alternar tema", en: "Toggle theme", es: "Cambiar tema" },
    language: { pt: "Idioma", en: "Language", es: "Idioma" },
    skip: { pt: "Pular para o conteúdo", en: "Skip to content", es: "Saltar al contenido" },
  },
} satisfies Record<string, Record<string, T>>;
